### ISSUE TITLE
No success messages

### ISSUE THREAD

**Issue by freMea** [E011011101001/Twitter-Block-With-Love#12] opened 2022-02-09 16:03 UTC
Nothing visually happens when user presses the **block** button. It’s misleading. It seems users are blocked but no success event is visually triggered while the message exists in the code.

**Comment by E011011101001** [comment] 2022-02-09 17:08
Thanks for your [translation](https://github.com/E011011101001/Twitter-Block-With-Love/issues/11#issue-1128699591). But it seems like the bug is caused by some wrong identifier labels like `like_list_identifier` you added in your local userscript, so I'm closing this issue.

You can wait before the next upgrade, which will be released soon.

**Closed by E011011101001** 2022-02-09 17:08 UTC
