### ISSUE TITLE
Stopped working again 

### ISSUE THREAD

**Issue by Nyantcha** [E011011101001/Twitter-Block-With-Love#25] opened 2024-01-21 01:06 UTC
Hi, not sure what happened because it was working fine just a few hours ago and now it stopped working again
I hope you can fix it 🙏

**Comment by E011011101001** [comment] 2024-01-21 07:19
Thanks for telling me and I have confirmed this bug is caused by X's API change.
I will fix it but the release may be at least two weeks later.

**Comment by Nyantcha** [comment] 2024-01-22 07:00
Thank you for your work!

**Comment by nwxz** [comment] 2024-02-18 10:59
Hey ! Just letting you know that your script has been deleted from GreasyFork (maybe you did it, i'm reporting it just in case).
Thanks for all your work, the world is waiting for tour update ! :)

**Comment by Nyantcha** [comment] 2024-02-24 11:00
> Hey ! Just letting you know that your script has been deleted from GreasyFork (maybe you did it, i'm reporting it just in case). Thanks for all your work, the world is waiting for your update ! :)
> 
> EDIT : I made a pull request, if interested !

Hey I saw that you forked the script and I would like to install it again, but I don’t know how to do that since I’m using a phone/don’t know how to install scripts from GitHub

**Comment by Aethyx12** [comment] 2024-02-27 05:59
This please!! help us !! :'(

**Comment by nwxz** [comment] 2024-02-28 00:36
Hey, i'm new on GitHub so I didn't know how to do everything. Anyway, while waiting for the pull request, you can install manually the forked script : 
[https://raw.githubusercontent.com/nwxz/Twitter-Block-With-Love-2024/master/index.user.js](https://raw.githubusercontent.com/nwxz/Twitter-Block-With-Love-2024/master/index.user.js)

**Comment by Nyantcha** [comment] 2024-02-28 06:45
Thank you! 

> Hey, i'm new on GitHub so I didn't know how to do everything. Anyway, while waiting for the pull request, you can install manually the forked script : https://raw.githubusercontent.com/nwxz/Twitter-Block-With-Love-2024/master/index.user.js

**Comment by E011011101001** [comment] 2024-02-28 07:18
I've merged the fix #27. Thank you @nwxz

**Closed by E011011101001** 2024-02-28 07:18 UTC
Labels: bug
